// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package model

import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"time"
)
var _ codegen.LatestVersion = codegen.Version[[0][17]struct{}]("You used 'weaver generate' codegen version 0.17.0, but you built your code with an incompatible weaver module version. Try upgrading 'weaver generate' and re-running it.")

// weaver.Instance checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Server stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Transaction)(nil)

type __is_Transaction[T ~struct {
	weaver.AutoMarshal
	FromAccountNum string    "gorm:\"column:from_acct;not null\""
	FromRoutingNum string    "gorm:\"column:from_route;not null\""
	ToAccountNum   string    "gorm:\"column:to_acct;not null\""
	ToRoutingNum   string    "gorm:\"column:to_route;not null\""
	Amount         int64     "gorm:\"column:amount;not null\""
	Timestamp      time.Time "gorm:\"column:timestamp;not null\""
}] struct{}

var _ __is_Transaction[Transaction]

func (x *Transaction) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Transaction.WeaverMarshal: nil receiver"))
	}
	enc.String(x.FromAccountNum)
	enc.String(x.FromRoutingNum)
	enc.String(x.ToAccountNum)
	enc.String(x.ToRoutingNum)
	enc.Int64(x.Amount)
	enc.EncodeBinaryMarshaler(&x.Timestamp)
}

func (x *Transaction) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Transaction.WeaverUnmarshal: nil receiver"))
	}
	x.FromAccountNum = dec.String()
	x.FromRoutingNum = dec.String()
	x.ToAccountNum = dec.String()
	x.ToRoutingNum = dec.String()
	x.Amount = dec.Int64()
	dec.DecodeBinaryUnmarshaler(&x.Timestamp)
}

var _ codegen.AutoMarshal = (*TransactionWithID)(nil)

type __is_TransactionWithID[T ~struct {
	weaver.AutoMarshal
	Transaction
	TransactionID int64 "gorm:\"column:transaction_id;primaryKey;autoIncrement:true\""
}] struct{}

var _ __is_TransactionWithID[TransactionWithID]

func (x *TransactionWithID) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("TransactionWithID.WeaverMarshal: nil receiver"))
	}
	(x.Transaction).WeaverMarshal(enc)
	enc.Int64(x.TransactionID)
}

func (x *TransactionWithID) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("TransactionWithID.WeaverUnmarshal: nil receiver"))
	}
	(&x.Transaction).WeaverUnmarshal(dec)
	x.TransactionID = dec.Int64()
}
